name: Backend Deploy
run-name: 🚀 Deploying

on:
  push:
    branches: [ "release" ]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [24.x]

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: ✅ Check out repository code
      uses: actions/checkout@v4
    
    # - name: 🧾 Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
        
    # - name: ✨ Install dependencies
    #   run: npm ci
    
    # - name: 🔨 Build Project
    #   run: npm run build -- --mode production
    
    # - name: 💻 Get Github Actions IP
    #   id: ip
    #   uses: haythem/public-ip@v1.2

    # - name: 🔧 Set Dist Filename
    #   id: dist
    #   run: |
    #     filename="calendar-engine-back-$(date +%Y%m%d_%H%M%S)"
    #     echo "dist_filename=$filename" >> $GITHUB_OUTPUT

    - name: 🔧 Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v3'
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
        workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}

    - name: 🔧 Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v3'

    # - name: 📦 Compress Build Files
    #   run: tar cvf ${{ steps.dist.outputs.dist_filename }}.tar -C ./dist .

    # - name: ⬆️ Upload to R2
    #   uses: ryand56/r2-upload-action@latest
    #   with:
    #     r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
    #     r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
    #     r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
    #     r2-bucket: ${{ secrets.R2_BUCKET }}
    #     source-dir: ./${{ steps.dist.outputs.dist_filename }}.tar
    #     destination-dir: artifacts

    - name: ✅ Test gcloud ssh
      env:
        R2_ENDPOINT_URL: https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
      run: |
        gcloud compute ssh ${{ secrets.GOOGLE_VM_NAME }} --zone=${{ secrets.GOOGLE_VM_REGION }} --command="
          export AWS_ACCESS_KEY_ID="${{ secrets.R2_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.R2_SECRET_ACCESS_KEY }}"

          aws s3 ls --endpoint-url $R2_ENDPOINT_URL
        "

